"""add_last_login_at

Revision ID: 331003611bd6
Revises: 484c69d43034
Create Date: 2026-03-18 02:29:44.245788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331003611bd6'
down_revision = '484c69d43034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
