backend:
  image: ghcr.io/jcruz2002/backend:lab07
  imagePullPolicy: Always
  replicas: 2
  port: 8080
frontend:
  image: ghcr.io/jcruz2002/frontend:lab07
  imagePullPolicy: Always
  replicas: 2
  port: 3000
service:
  port: 80
ingress:
  enabled: true
  className: nginx
  host: app.local
