# values-dev.yaml - Valores para ambiente desarrollo (minikube local)

backend:
  image: ghcr.io/jcruz2002/backend:lab07
  imagePullPolicy: IfNotPresent
  replicas: 1  # 1 para minikube local
  port: 8080

frontend:
  image: ghcr.io/jcruz2002/frontend:lab07
  imagePullPolicy: IfNotPresent
  replicas: 1  # 1 para minikube local
  port: 3000

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  host: enrollmenthub.local
