apiVersion: apps/v1
kind: Deployment
metadata: { name: app-next, labels: { app: app-next } }
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector: { matchLabels: { app: app-next } }
  template:
    metadata: { labels: { app: app-next, gitops-change: "lab10-resync-1" } }
    spec:
      containers:
      - name: web
        image: {{ .Values.frontend.image }}
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy | default "Always" }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.port }}
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
