apiVersion: v1
kind: Service
metadata: 
  name: app-next
  labels: { app: app-next }
spec:
  type: ClusterIP
  selector: { app: app-next }
  ports: 
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-dotnet
  labels: { app: api-dotnet }
spec:
  type: ClusterIP
  selector: { app: api-dotnet }
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.backend.port }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enrollmenthub
  labels: { app: enrollmenthub }
  annotations: 
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-next
            port: { number: {{ .Values.service.port }} }
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-dotnet
            port: { number: {{ .Values.service.port }} }
{{- end }}
