{
 "title": "Bootcamp API Overview",
 "tags": [
  "bootcamp",
  "observabilidad"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disponibilidad API (up)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"api-dotnet\"}",
     "legendFormat": "api-dotnet"
    }
   ]
  },
  {
   "title": "Requests por segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"api-dotnet\"}[1m]))",
     "legendFormat": "RPS total"
    }
   ]
  },
  {
   "title": "Tasa de respuestas por código HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"api-dotnet\"}[5m])) by (code)",
     "legendFormat": "code={{code}}"
    }
   ]
  }
 ]
}